# Generated by Django 5.2.9 on 2025-12-21 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyMembershipCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_memberships', to='characters.character')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_memberships', to='lobbys.lobby')),
            ],
            options={
                'unique_together': {('character', 'lobby')},
            },
        ),
        migrations.CreateModel(
            name='LobbyMembershipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='lobbys.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lobbys.lobbyrole')),
            ],
            options={
                'unique_together': {('user', 'lobby')},
            },
        ),
    ]
