# Generated by Django 5.2.7 on 2025-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlefield', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('group', 'position_x', 'position_y'), name='unique_position_in_group'),
        ),
    ]
