# Generated by Django 5.2.9 on 2025-12-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battlefield', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='groups.group'),
        ),
        migrations.AddField(
            model_name='characterposition',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_positions', to='battlefield.location'),
        ),
        migrations.AlterUniqueTogether(
            name='characterposition',
            unique_together={('character', 'location')},
        ),
    ]
