# Generated by Django 5.2.9 on 2025-12-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copper_coins', models.IntegerField(default=0)),
                ('silver_coins', models.IntegerField(default=0)),
                ('electrum_coins', models.IntegerField(default=0)),
                ('gold_coins', models.IntegerField(default=0)),
                ('platinum_coins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('atack_roll', models.CharField(max_length=10)),
                ('damage_dice', models.CharField(max_length=10)),
                ('damage_dice_count', models.IntegerField(default=1)),
                ('damage_modificator', models.IntegerField(default=0)),
                ('saving_throw', models.CharField(max_length=5)),
                ('is_using_spell_circle', models.BooleanField(default=False)),
                ('required_spell_circle', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSpellCircleSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_1', models.IntegerField(default=0)),
                ('circle_2', models.IntegerField(default=0)),
                ('circle_3', models.IntegerField(default=0)),
                ('circle_4', models.IntegerField(default=0)),
                ('circle_5', models.IntegerField(default=0)),
                ('circle_6', models.IntegerField(default=0)),
                ('circle_7', models.IntegerField(default=0)),
                ('circle_8', models.IntegerField(default=0)),
                ('circle_9', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=50)),
                ('atack_roll', models.CharField(max_length=10)),
                ('damage_dice', models.CharField(max_length=10)),
                ('damage_dice_count', models.IntegerField(default=1)),
                ('damage_modificator', models.IntegerField(default=0)),
                ('saving_throw', models.CharField(max_length=5)),
                ('is_using_spell_circle', models.BooleanField(default=True)),
                ('required_spell_circle', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('mastery', models.IntegerField(default=2)),
                ('dificulty_save_throw', models.IntegerField(default=0)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('movement_speed', models.IntegerField(default=0)),
                ('max_hit_points', models.IntegerField(default=0)),
                ('current_hit_points', models.IntegerField(default=0)),
                ('character_class', models.CharField(blank=True, max_length=15, null=True)),
                ('character_sub_class', models.CharField(blank=True, max_length=15, null=True)),
                ('armor_class', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='characters.charactermoney')),
                ('spell_circle_slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='characters.characterspellcircleslots')),
                ('stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='characters.characterstats')),
            ],
        ),
    ]
