# Generated by Django 5.2.9 on 2025-12-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='character_name',
        ),
    ]
