# Generated by Django 5.2.9 on 2025-12-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_name_character_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('character_class', models.CharField(blank=True, max_length=15, null=True)),
                ('character_sub_class', models.CharField(blank=True, max_length=15, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('alignment', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('mastery', models.IntegerField(default=2)),
                ('dificulty_save_throw', models.IntegerField(default=0)),
                ('max_hit_points', models.IntegerField(default=0)),
                ('armor_class', models.IntegerField(default=0)),
                ('movement_speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='armor_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_sub_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dificulty_save_throw',
        ),
        migrations.RemoveField(
            model_name='character',
            name='height',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mastery',
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_hit_points',
        ),
        migrations.RemoveField(
            model_name='character',
            name='movement_speed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='size',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weight',
        ),
        migrations.AddField(
            model_name='character',
            name='entity_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='characters.entitybase'),
        ),
    ]
